[package]
name    = "badge_2021_rs"
version = "0.1.0"
authors = ["Daniel Maslowski <info@orangecms.org>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
panic-halt   = "0.2"
esp32-hal = { package = "esp32-hal", git = "https://github.com/esp-rs/esp-hal.git" }
xtensa-lx-rt = { version = "0.9", features = ["esp32"], optional = true }
nb = "1.0.0"

[features]
default = ["rt"]
rt = ["xtensa-lx-rt"]
